
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sellerdb}
    username: ${SPRING_DATASOURCE_USERNAME:selleruser}
    password: ${SPRING_DATASOURCE_PASSWORD:sellerpass}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata
server:
  port: 8080

  cache:
    type: caffeine
